.TH "my_cbc_tools.kde_data" 3 "Thu Sep 26 2019" "Version 0.0.1" "my_cbc_tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_cbc_tools.kde_data
.SH SYNOPSIS
.br
.PP
.PP
Inherits rv_continuous\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, data, \fBlower\fP=None, \fBupper\fP=None, **kargs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlower\fP"
.br
.ti -1c
.RI "\fBupper\fP"
.br
.ti -1c
.RI "\fBkde\fP"
.br
.ti -1c
.RI "\fBscale\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1307 of file my_cbc_tools\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def my_cbc_tools\&.kde_data\&.__init__ ( self,  data,  lower = \fCNone\fP,  upper = \fCNone\fP, ** kargs)"

.PP
.nf
Re-sample data from kde of a group of data 

.fi
.PP
 
.PP
Definition at line 1308 of file my_cbc_tools\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "my_cbc_tools\&.kde_data\&.kde"

.PP
Definition at line 1317 of file my_cbc_tools\&.py\&.
.SS "my_cbc_tools\&.kde_data\&.lower"

.PP
Definition at line 1315 of file my_cbc_tools\&.py\&.
.SS "my_cbc_tools\&.kde_data\&.scale"

.PP
Definition at line 1318 of file my_cbc_tools\&.py\&.
.SS "my_cbc_tools\&.kde_data\&.upper"

.PP
Definition at line 1316 of file my_cbc_tools\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for my_cbc_tools from the source code\&.
